---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tower-container-group
subjects:
  - kind: ServiceAccount
    name: tower-container-group
    namespace: tower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-manager
